[application]

name = "ipinfo"

default_platform = "web"

out_dir = "dist"

asset_dir = "assets"

[web.app]
title = "ipinfo"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = ["assets/tailwind.css"]
script = []

[web.resource.dev]

script = []
